"""Dựng VIDEO MẪU cho hai cổng kiểm chạy thật — dự án tự sở hữu hoàn toàn.

Vì sao có tệp này (giới hạn (1) của `docs/TEST_LOG.md` mục I0-FDE(e)):
`tap01_clip.mp4` vào repo ở commit `190cd2a` **không kèm ghi chú nguồn**, tên
"tap01" gợi ý một tập phim của bên thứ ba. Guardrail 11 của mini-spec I0-FDE
đòi video mẫu bắt buộc phải là *project-owned or explicitly permitted*. Không
tra được nguồn thì không khẳng định được gì — nên thay vì đoán, dựng hẳn một
video mẫu mà **mọi thành phần đều do dự án tạo ra**:

* **Lời thoại**: 8 câu tiếng Anh viết trong chính tệp này.
* **Tiếng**: eSpeak NG đọc 8 câu đó. eSpeak NG là bộ tổng hợp **formant** —
  nó tính ra sóng âm từ quy tắc ngữ âm, **không phát lại bản thu của ai**.
* **Hình**: nền một màu + chữ do ffmpeg vẽ.

Không có khung hình, giọng nói hay câu chữ nào của bên thứ ba trong tệp ra.

## Video mẫu phải giữ được ĐÚNG những tính chất nào

Đây là phần dễ làm hỏng nhất: đổi sang một tệp "sạch bản quyền" nhưng làm các
chốt của hai cổng mất khả năng phân biệt đạt/hỏng thì là đánh đổi ngầm. Bốn
tính chất bắt buộc, mỗi cái gắn với một chốt có thật:

1. **Tiếng nói KHÔNG phải tiếng Việt.** `pipeline.py` bỏ hẳn khâu dịch khi
   ngôn ngữ nghe ra trùng ngôn ngữ đích và độ tin cậy ≥ 0,85
   (`cung_ngon_ngu` → `khong_can_dich`). Video mẫu tiếng Việt sẽ làm lượt chạy
   **không đi qua đường dịch tay**, và cả hai cổng đều đòi đúng đường đó
   (`TRANSLATE_PENDING.txt`, trạng thái `translate_pending`). Nên mẫu phải là
   một ngôn ngữ khác — ở đây là tiếng Anh, y như mẫu cũ.
2. **Nghe ra được NHIỀU câu**, không phải một câu. Chốt "nghe được N câu" và
   phần đóng vai dịch tay (xoay vòng 3 câu tiếng Việt theo từng đoạn) chỉ có
   nghĩa khi bản chép lời có nhiều đoạn. Mẫu cũ cho **8 đoạn**; mẫu này giữ
   đúng 8 câu, mỗi câu 3–9 giây, xen khoảng lặng.
3. **Đủ dài để hai ngưỡng còn phân biệt được.** Ngưỡng câm (-70 dB) và ngưỡng
   lệch thời lượng (35%) đo trên **cả tệp**: với mẫu 2–3 giây thì 35% chỉ còn
   là một giây, mà chính giọng đọc tiếng Việt thay vào cũng đã lệch hơn thế —
   chốt sẽ kêu oan; còn mức âm trung bình của một tệp quá ngắn thì một đoạn
   hỏng cũng đủ kéo cả tệp xuống. Giữ **~53 giây**, đúng cỡ mẫu cũ (53,5 s),
   để các số đo lịch sử trong `docs/TEST_LOG.md` còn so sánh được.
4. **Có khoảng lặng giữa các câu.** Bước ghép dồn phần trễ của giọng đọc vào
   khoảng lặng; mẫu nói liên tục không khoảng nghỉ sẽ đẩy thời lượng ra xa và
   làm chốt 35% kêu oan (đúng cơ chế đã ghi trong mini-spec D1).

Chạy lại::

    python scripts/tao_mau_kiem_chay.py            # dựng + ghi manifest
    python scripts/tao_mau_kiem_chay.py --do-asr   # + đo lại bằng Whisper

Cần `espeak-ng` và `ffmpeg` trên máy dựng. **Máy chạy CI không cần** — tệp ra
được commit vào repo.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

GOC_REPO = Path(__file__).resolve().parents[1]

#: Tên tệp mẫu (hai cổng kiểm lấy đây làm mặc định).
TEN_MAU = "mau_kiem_chay.mp4"
TEN_MANIFEST = "mau_kiem_chay.json"

#: Lời thoại — do dự án viết. Cố ý **tiếng Anh** (xem tính chất 1 ở đầu tệp)
#: và cố ý nói về chính lượt kiểm: ai mở tệp ra nghe cũng biết ngay nó là gì,
#: không ai nhầm nó với nội dung của người khác.
#:
#: Dòng tiếng Việt đi kèm được **vẽ lên hình** cùng dòng tiếng Anh: mẫu cũ có
#: phụ đề cháy song ngữ và các pilot OCR (H2a/H2b) dựa vào đó, nên mẫu mới
#: giữ lại tính chất ấy — kèm đủ dấu tiếng Việt, thứ H2b cần.
LOI_THOAI = [
    ("This clip is a test fixture owned by the VoxDub Studio project.",
     "Đây là video mẫu do chính dự án VoxDub Studio tạo ra."),
    ("Every part of it was generated by a script in this repository.",
     "Mọi thành phần của nó đều do một script trong kho mã này sinh ra."),
    ("The speech you hear is synthetic, so no recording of any person is used.",
     "Giọng nói bạn nghe là giọng tổng hợp, không dùng bản thu của ai."),
    ("The dubbing pipeline should hear several separate sentences here.",
     "Đường lồng tiếng phải nghe ra được vài câu tách rời ở đây."),
    ("Each sentence is followed by a short pause, on purpose.",
     "Sau mỗi câu là một khoảng lặng ngắn, và đó là cố ý."),
    ("Those pauses let the Vietnamese voice fit without stretching the video.",
     "Khoảng lặng đó để giọng đọc tiếng Việt vừa vào mà không kéo dài video."),
    ("If the exported file is silent, the release gate must fail.",
     "Nếu tệp xuất ra bị câm thì cổng phát hành phải báo hỏng."),
    ("This is the end of the fixture, thank you for listening.",
     "Đây là hết video mẫu, cảm ơn bạn đã nghe."),
]

#: Khoảng lặng TRƯỚC mỗi câu (giây). Câu đầu có một nhịp lặng để bước nghe
#: không phải bắt đúng mẫu ở giây 0.
KHOANG_LANG = [1.4, 2.0, 1.6, 2.2, 1.8, 2.4, 1.7, 2.1]

#: Khoảng lặng ở đuôi — giữ cho tổng thời lượng ≈ mẫu cũ (53,5 s).
LANG_CUOI = 2.0

#: Giọng + tốc độ eSpeak. Chậm hơn mặc định (175) vì bộ nghe `tiny` của CI là
#: model nhỏ nhất — đo thật: ở tốc độ mặc định nó nuốt chữ nhiều hơn hẳn.
GIONG_ESPEAK = "en-us"
TOC_DO = 145

#: Hình: nhỏ và tĩnh cho nhẹ repo, nhưng vẫn đúng dạng h264 + aac như tệp
#: người dùng đưa vào.
RONG, CAO, FPS = 640, 360, 24
NEN = "0x101820"
PHONG = "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf"


def _chay(lenh: list[str]) -> subprocess.CompletedProcess:
    kq = subprocess.run(lenh, capture_output=True, text=True,
                        encoding="utf-8", errors="replace")
    if kq.returncode != 0:
        raise RuntimeError(f"{lenh[0]} lỗi ({kq.returncode}):\n"
                           f"{(kq.stderr or '')[-1500:]}")
    return kq


def _giay(tep: Path) -> float:
    ra = _chay(["ffprobe", "-v", "error", "-show_entries", "format=duration",
                "-of", "default=nw=1:nk=1", str(tep)]).stdout.strip()
    return float(ra.splitlines()[0])


def _bam(tep: Path) -> str:
    h = hashlib.sha256()
    with open(tep, "rb") as f:
        for khoi in iter(lambda: f.read(1 << 20), b""):
            h.update(khoi)
    return h.hexdigest()


def _thoat(chu: str) -> str:
    """Thoát chuỗi cho bộ lọc drawtext của ffmpeg."""
    return (chu.replace("\\", "\\\\").replace(":", "\\:")
            .replace("'", "’").replace(",", "\\,"))


def dung_tieng(tam: Path) -> tuple[Path, list[dict]]:
    """Đọc 8 câu bằng eSpeak NG rồi xếp thành MỘT dải tiếng có khoảng lặng."""
    phan: list[str] = []
    moc: list[dict] = []
    t = 0.0
    danh_sach = tam / "ghep.txt"
    for i, ((en, _vi), lang) in enumerate(zip(LOI_THOAI, KHOANG_LANG)):
        im = tam / f"lang_{i}.wav"
        _chay(["ffmpeg", "-y", "-v", "error", "-f", "lavfi", "-i",
               f"anullsrc=r=22050:cl=mono:d={lang}", "-c:a", "pcm_s16le",
               str(im)])
        noi = tam / f"cau_{i}.wav"
        _chay(["espeak-ng", "-v", GIONG_ESPEAK, "-s", str(TOC_DO),
               "-w", str(noi), en])
        dai = _giay(noi)
        moc.append({"thu_tu": i + 1, "bat_dau": round(t + lang, 3),
                    "ket_thuc": round(t + lang + dai, 3),
                    "giay": round(dai, 3), "loi_en": en, "loi_vi": LOI_THOAI[i][1]})
        t += lang + dai
        phan += [str(im), str(noi)]

    duoi = tam / "lang_cuoi.wav"
    _chay(["ffmpeg", "-y", "-v", "error", "-f", "lavfi", "-i",
           f"anullsrc=r=22050:cl=mono:d={LANG_CUOI}", "-c:a", "pcm_s16le",
           str(duoi)])
    phan.append(str(duoi))

    danh_sach.write_text(
        "".join(f"file '{p}'\n" for p in phan), encoding="utf-8")
    tieng = tam / "tieng.wav"
    _chay(["ffmpeg", "-y", "-v", "error", "-f", "concat", "-safe", "0",
           "-i", str(danh_sach), "-c:a", "pcm_s16le", str(tieng)])
    return tieng, moc


def dung_video(tam: Path, tieng: Path, moc: list[dict], ra: Path) -> None:
    """Vẽ hình + ghép tiếng thành tệp h264/aac như video người dùng đưa vào."""
    tong = _giay(tieng)
    loc = [f"color=c={NEN}:s={RONG}x{CAO}:r={FPS}:d={tong:.3f}[nen]"]
    truoc = "nen"
    # Tiêu đề đứng yên suốt clip — mở tệp ra là biết ngay nó là cái gì.
    loc.append(
        f"[{truoc}]drawtext=fontfile={PHONG}:"
        f"text='{_thoat('VoxDub Studio — video mẫu kiểm chạy')}':"
        f"fontcolor=0x8fb3d9:fontsize=22:x=(w-text_w)/2:y=28[tieude]")
    truoc = "tieude"
    # Phụ đề CHÁY song ngữ, đúng tính chất mà mẫu cũ có (pilot OCR H2a/H2b).
    for i, m in enumerate(moc):
        for dong, (chu, mau, y) in enumerate((
                (m["loi_en"], "0xffffff", CAO - 96),
                (m["loi_vi"], "0xffe08a", CAO - 58))):
            nhan = f"t{i}_{dong}"
            loc.append(
                f"[{truoc}]drawtext=fontfile={PHONG}:text='{_thoat(chu)}':"
                f"fontcolor={mau}:fontsize=18:x=(w-text_w)/2:y={y}:"
                f"box=1:boxcolor=0x000000@0.55:boxborderw=8:"
                f"enable='between(t,{m['bat_dau']:.3f},{m['ket_thuc']:.3f})'"
                f"[{nhan}]")
            truoc = nhan
    loc.append(f"[{truoc}]format=yuv420p[v]")
    _chay(["ffmpeg", "-y", "-v", "error",
           "-f", "lavfi", "-i", f"anullsrc=r=44100:cl=stereo:d={tong:.3f}",
           "-i", str(tieng),
           "-filter_complex", ";".join(loc)
           + ";[1:a]aresample=44100,aformat=channel_layouts=stereo[a]",
           "-map", "[v]", "-map", "[a]",
           "-c:v", "libx264", "-preset", "veryslow", "-crf", "30",
           "-pix_fmt", "yuv420p", "-c:a", "aac", "-b:a", "96k",
           "-movflags", "+faststart", "-shortest", str(ra)])


def do_bang_whisper(video: Path) -> dict:
    """Đo lại bằng chính bộ nghe của CI (`tiny`) — số này đi vào manifest.

    Không có `.venv-whisper` thì bỏ qua: đây là phần *ghi nhận*, không phải
    phần dựng. Nhưng thiếu nó thì manifest phải nói là thiếu, chứ không được
    im lặng như thể đã đo.
    """
    py = GOC_REPO / ".venv-whisper" / ("Scripts/python.exe" if os.name == "nt"
                                       else "bin/python")
    if not py.is_file():
        return {"da_do": False, "ly_do": f"không có {py}"}
    ma = (
        "import json,os,sys\n"
        f"os.environ['HF_HOME']={str(GOC_REPO / 'models' / 'whisper')!r}\n"
        "from faster_whisper import WhisperModel\n"
        f"m=WhisperModel('tiny',device='cpu',compute_type='int8',"
        f"download_root={str(GOC_REPO / 'models' / 'whisper')!r})\n"
        f"segs,info=m.transcribe({str(video)!r},language=None)\n"
        "segs=[{'bat_dau':round(s.start,2),'ket_thuc':round(s.end,2),"
        "'chu':s.text.strip()} for s in segs]\n"
        "print(json.dumps({'da_do':True,'ngon_ngu':info.language,"
        "'do_tin_cay':round(info.language_probability,4),'so_cau':len(segs),"
        "'cac_cau':segs},ensure_ascii=False))\n")
    kq = subprocess.run([str(py), "-c", ma], capture_output=True, text=True,
                        encoding="utf-8", errors="replace", timeout=900)
    try:
        return json.loads((kq.stdout or "").strip().splitlines()[-1])
    except (ValueError, IndexError):
        return {"da_do": False, "ly_do": (kq.stderr or "")[-500:]}


def phien_ban_cong_cu() -> dict:
    ra = {}
    for ten, lenh in (("espeak_ng", ["espeak-ng", "--version"]),
                      ("ffmpeg", ["ffmpeg", "-version"])):
        try:
            ra[ten] = subprocess.run(lenh, capture_output=True, text=True,
                                     encoding="utf-8", errors="replace"
                                     ).stdout.splitlines()[0].strip()
        except OSError:
            ra[ten] = "(không chạy được)"
    return ra


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--ra", default=str(GOC_REPO / TEN_MAU))
    ap.add_argument("--do-asr", action="store_true",
                    help="đo lại bằng Whisper tiny rồi ghi vào manifest")
    args = ap.parse_args(argv)

    for cong_cu in ("espeak-ng", "ffmpeg", "ffprobe"):
        if not shutil.which(cong_cu):
            print(f"!! thiếu {cong_cu} trên máy dựng", file=sys.stderr)
            return 2
    if not Path(PHONG).is_file():
        print(f"!! thiếu phông {PHONG}", file=sys.stderr)
        return 2

    ra = Path(args.ra)
    tam = Path(tempfile.mkdtemp(prefix="mau_kiem_chay_"))
    try:
        tieng, moc = dung_tieng(tam)
        dung_video(tam, tieng, moc, ra)
    finally:
        shutil.rmtree(tam, ignore_errors=True)

    ho_so = {
        "tep": ra.name,
        "so_huu": "Dự án VoxDub Studio (voidmix) — tự dựng, không dùng tư "
                  "liệu của bên thứ ba",
        "co_so_phap_ly": {
            "loi_thoai": "do dự án viết, nằm trong scripts/tao_mau_kiem_chay.py",
            "tieng": "eSpeak NG tổng hợp theo quy tắc ngữ âm (formant) — "
                     "không phát lại bản thu của bất kỳ ai",
            "hinh": "ffmpeg vẽ: nền một màu + chữ, không có khung hình quay "
                    "từ nguồn nào",
            "ghi_chu": "Bản thân eSpeak NG (GPLv3) và ffmpeg là CÔNG CỤ; "
                       "giấy phép của chúng ràng buộc phần mềm, không ràng "
                       "buộc sóng âm/khung hình do dự án sinh ra.",
        },
        "dung_bang": "python scripts/tao_mau_kiem_chay.py",
        "cong_cu": phien_ban_cong_cu(),
        "giay": round(_giay(ra), 3),
        "byte": ra.stat().st_size,
        "sha256": _bam(ra),
        "so_cau_thiet_ke": len(LOI_THOAI),
        "giong_espeak": GIONG_ESPEAK,
        "toc_do_espeak": TOC_DO,
        "loi_thoai": moc,
    }
    if args.do_asr:
        ho_so["do_bang_whisper_tiny"] = do_bang_whisper(ra)
    (ra.parent / TEN_MANIFEST).write_text(
        json.dumps(ho_so, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8")
    print(f"[mẫu] {ra} · {ho_so['giay']:.2f}s · {ho_so['byte']} byte · "
          f"sha256 {ho_so['sha256'][:16]}…")
    if args.do_asr:
        d = ho_so["do_bang_whisper_tiny"]
        print(f"[mẫu] Whisper tiny: {d.get('ngon_ngu')} "
              f"({d.get('do_tin_cay')}) · {d.get('so_cau')} câu"
              if d.get("da_do") else f"[mẫu] CHƯA đo được: {d.get('ly_do')}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
